# Don't modify this file. If you do, your game may not start.
[TdGame.TdMove]
SpeedModifier=1.f
FrictionModifier=1.f
RedoMoveTime = 0.f
bStickyAim=true
StickyAngle=800
StickyAimedModifier=0.0

# AiAimPenalties: 1.0 = no change (default stormtrooper aim), 0.0 = freeze aim improvement, 0.5 = halve aim improvement, etc...
# This is active for the duration of the move
AiAimPenalties = (Easy = 1.0, Medium = 1.0, Hard = 1.0)

# AiAimOneShotPenalties:  0.0 = No change, 40.0 = subtract 40 from deviation when the move is performed
# This is applied once at the beginning of a move
AiAimOneShotPenalties = (Easy = 0.0, Medium = 0.0, Hard = 0.0)

FireAnimSeqName = "standfire"
ReloadAnimSeqName = "reload"
bTriggersCompliment = false

[TdGame.TdMove_Walking]
FrictionModifier=1.0
TriggerIdleAnimMinTime = 30.f
TriggerIdleAnimMaxTime = 40.f
UnarmedIdleAnims=(AnimName="standidle1",NodeType=CNT_Canned,bResetCameraLook=true)
UnarmedIdleAnims=(AnimName="standidle2",NodeType=CNT_Canned,bResetCameraLook=true)
UnarmedIdleAnims=(AnimName="standidle3",NodeType=CNT_Canned,bResetCameraLook=true)

[TdGame.TdMove_Crouch]
SpeedModifier=0.2f
IntoCrouchSitTime = 1.0


[TdGame.TdMove_180Turn]
FrictionModifier=0.3f
TurnTime = 0.25
TurnAnimBlendInTime=0.2
TurnAnimBlendOutTime=0.2
RedoMoveTime = 0.5f


[TdGame.TdMove_Falling]
EnterToFallingZSpeed = - 200
RollLandingTimeThreshold = 2.0
MaximumSpeedForRollLanding = -5000


[TdGame.TdMove_Jump]
# Upwards velocity when unarmed or with light weapon
BaseJumpZ=630.0
# Upwards velocity with heavy weapon
BaseJumpZHeavy=430.0
JumpAddXY=100
bCheckForGrab = true
bCheckForVaultOver = true
LongJumpSlowThreshold = 400
LongJumpNormalThreshold = 500
LongJumpFastThreshold = 700
JumpBlendInTime = 0.1
JumpBlendOutTime = 0.2
JumpStillBlendOutTime = 0.2
bCheckForWallClimb = true
AiAimPenalties = (Easy = 0.7, Medium = 0.8, Hard = 1.0)

[TdGame.TdMove_BotJump]
bCheckForGrab = true
bCheckForVaultOver = true

[TdGame.TdMove_DodgeJump]
BaseJumpZ=300.0
JumpAddXY=600.0
DodgeJumpInertiaConservation = 0.3
StrafeThreshold = 0.99
bCheckForGrab = false
bCheckForVaultOver = false
JumpBlendInTime = 0.1
JumpBlendOutTime = 0.2
RedoMoveTime = 0.3f
bTriggersCompliment = false
LookAtAIVelThreshold = 200
LookAtAITraceDistance = 250
LookAtAIRadiusThreshold = 90
AiAimOneShotPenalties = (Easy = 75.0, Medium = 75.0, Hard = 75.0)

[TdGame.TdMove_SpringBoard]
SpringBoardMaxHeight=148
SpringBoardMinHeight=80
SpringBoardJumpZ=950
SpringBoardJumpXYAdd=-100
SpringBoardJumpXYMin=400
IntermediateFootPlantHeight=64
IntermediateFootPlantDistance=112
CheckDistanceTime=1.0f
bCheckForVaultOver = true
bCheckForGrab = true
bCheckForWallClimb = true
bTriggersCompliment = true
AiAimPenalties = (Easy = 0.3, Medium = 0.4, Hard = 0.6)
AiAimOneShotPenalties = (Easy = 75.0, Medium = 75.0, Hard = 75.0)

[TdGame.TdMove_WallKick]
WallKickMaxDistance=60
WallKickVelocity2D=300
WallKickVelocityZ=580
WallKickCheckHeight=90
WallKickExtentWidth=20
WallKickExtentHeight=10
bCheckForGrab=true
bCheckForVaultOver=true
RedoMoveTime = 1.f
bTriggersCompliment = true

[TdGame.TdPhysicsMove]
#HandPlantExtentCheckHeight = 148
HandPlantExtentCheckHeight = 80
HandPlantExtentCheckWidth = 10
HandPlantCheckDistance = 200
HandPlantCheckHeight = 112
ContextMoveDistanceMultiplier = 1.8
bCheckForGrab = false
bCheckForEdgeInVelDir = false
bCheckForWallClimb = false



[TdGame.TdMove_WallRun]
WallRunningForwardCheckDistance=50
WallRunningStrafeCheckDistance=50
WallRunningMinWallHeight=192
WallRunningMinSpeed = 200
WallRunningVelocityStartLimit=300
WallRunningVelocityStopLimit=-500
WallRunningForwardMinStartAngle=0
WallRunningForwardMaxStartAngle=57
WallRunningStrafeStartAngle=60
WallRunningHorisontalFriction=0.05
WallRunningHorisontalInitialZHeight=170
WallRunningHorisontalAcceleration=820
WallRunningHorisontalDeceleration=500
WallRunningHorisontalAlignSpeed=700
WallRunningDistanceForIntoWall = 180
WallRunningRotatePawnAlongWallTime = 0.4
WallRunningDelayPawnRotationTime = 0.01
WallRunningMoveToIntoPositionDegreeThreshold = 70
WallRunningIntoWallrunBlendInTime = 0.2
WallRunningIntoWallrunBlendOutTime = 0.2
PlayCameraHitWallEffect = true
MinimumVelocityIntoWall = 600
MaximumVelocityIntoWall = 700
WallrunStartUpperBodyAnimPlayRate = 0.6
LookAlongWallInterpolationTime = 0.2
AiAimPenalties = (Easy = 0.4, Medium = 0.5, Hard = 0.7)
StickyAngle=4000
StickyAimedModifier=1.0

RedoMoveTime=0.15
TimeToDo90Turn=0.25
bTriggersCompliment = false

[TdGame.TdMove_WallClimb]
WallClimbingMaxDistance2D=120
WallClimbingVelocityStartLimit = 0
WallClimbingVerticalStartAngle=33 //55
WallClimbingVerticalFriction=6
AddOnSpeed2DHeight = 60
AddOnSpeed2DMaxLimit = 650
AddOnSpeedZHeight = 130
AddOnSpeedZMaxLimit = 320
WallClimbingGravity = 800
bCheckForVaultOver = true
bCheckForGrab = true
bCheckForEdgeInVelDir = true
HandPlantCheckHeight = 112
MinLegdeZNormal=0.707
MinWallHeight=180
bTriggersCompliment = false
FrictionModifier = 0.3f
MinUpwardsVelocityToDoubleJump= 100
MaxIntoWallClimbVelocityToDoubleJump = 100
AiAimPenalties = (Easy = 0.4, Medium = 0.5, Hard = 0.7)

[TdGame.TdMove_WallrunJump]
WallRunningJumpOffZHeightForward=100
WallRunningJumpOffZHeightMaxAddTurned = 60
WallRunningPushAwaySpeedNoob= 120
WallRunningPushAwaySpeedProAdd=400
WallRunningPushForwardSpeedMin=0.1
bCheckForGrab = true
bCheckForVaultOver = true
bCheckForWallClimb = true
bCheckForWallClimb = true
bTriggersCompliment = false
AiAimOneShotPenalties = (Easy = 75.0, Medium = 75.0, Hard = 75.0)

[TdGame.TdMove_WallrunDodgeJump]
BaseJumpZ=300.0
JumpAddXY=600.0
DodgeJumpInertiaConservation = 0.3
bCheckForGrab = false
bCheckForVaultOver = false
JumpBlendInTime = 0.0
JumpBlendOutTime = 0.0
bTriggersCompliment = true
AiAimOneShotPenalties = (Easy = 75.0, Medium = 75.0, Hard = 75.0)

[TdGame.TdMove_WallClimbDodgeJump]
BaseJumpZ=700.0
JumpAddXY=150.0
DodgeJumpInertiaConservation = 1.0
bCheckForGrab = true
bCheckForVaultOver = true
bCheckForWallClimb = true
JumpBlendInTime = 0.2
JumpBlendOutTime = 0.2
bTriggersCompliment = true
AiAimOneShotPenalties = (Easy = 75.0, Medium = 75.0, Hard = 75.0)

[TdGame.TdMove_WallClimb180TurnJump]
JumpOffZHeight = 250
JumpPushAwaySpeed= 400
JumpTimeWindow=0.6
bCheckForGrab = true
bCheckForVaultOver = true
bCheckForWallClimb = true
RedoMoveTime = 1.0
bTriggersCompliment = true
AiAimPenalties = (Easy = 0.3, Medium = 0.4, Hard = 0.6)
AiAimOneShotPenalties = (Easy = 100.0, Medium = 100.0, Hard = 100.0)

[TdGame.TdMove_Falling]
bCheckForGrab = true
bCheckForVaultOver = true

[TdGame.TdMove_IntoGrab]
IntoGrabAlignSpeed = 300
IntoGrabMaxAngle = 70
IntoGrabMinInitialAlignSpeed = -3000
GrabMinGrabableZNormal = 0.707
GrabDesiredLedgeOffset = (X=30.0000000,Y=0.000000,Z=92.800000)
MinGrabLedgeAdjustDistance = 32
IntoGrabMaxDistance = 200
IntoGrabZVelocityThreshold = 150
IntoGrabBelowEdgeZVelocityThreshold = 800
HangFoldedIntoGrabZSpeedThreshold = 150
HangFoldedIntoGrabSpeed2DThreshold = 50
HangFoldedUpperDeltaDistance = 35
HangFoldedLowerDeltaDistance = 70
HangFoldedDownwardSpeedLimit = -300
HangFoldedMaxDistance = 60
bCheckForVaultOver = true
HangImpactMinZSpeed = -600		#HangHardStart2
HangHardImpactMinZSpeed = -1000		#HangHardStart3

[TdGame.TdMove_IntoGrabBot]
IntoGrabMaxAngle=90

[TdGame.TdMove_Grab]
GrabMaxAngle = 40
GrabDesiredLedgeOffset = (X=30.0000000,Y=0.000000,Z=92.800000)
RedoMoveTime = 0.15
StartTurningAngle = 16384
HangFreeZDistanceCheck = 128

[TdGame.TdMove_SpeedVault]
VaultClearObjectHeight = 35
bTriggersCompliment = false
MaxTimeToLedge = 0.4
VaultTypes = (AnimName="autostepuprightleg", bVaultOnto = true,	MinHeight=0,	MaxHeight=48,	MinSpeedZ=-600, 	MaxSpeedZ=0,		MaxDistanceTime=0.2f,	ClampSpeedMin=100, ClampSpeedMax=300, VaultTimeUp=0.0,	VaultTimeOver=0.3, VaultTimeDown=0.2,	OverObstacleTime=0.2,		HandplantOffset=(X=0.f,Y=0.f,Z=5.f), 		HandIKOffset=(X=0.f,Y=0.f,Z=0.f),	LedgeOffset=(X=0.f,Y=0.f,Z=90.f),	bLeftHandIK=false,	bRightHandIK=false )
VaultTypes = (AnimName="stepuprightleg88", bVaultOnto = true,	MinHeight=48,	MaxHeight=148,	MinSpeedZ=0,	MaxSpeedZ=700,	MaxMomentum = 200.f, 	MaxDistanceTime=0.4f,	ClampSpeedMin=200, 	ClampSpeedMax=700, VaultTimeOver=0.4, VaultTimeDown=0.25,	OverObstacleTime = 0.2, LedgeOffset=(X=0.f,Y=-20.f,Z=60.f))
VaultTypes = (AnimName="vaultOnto", bVaultOnto = true,	MinHeight=64,	MaxHeight=148,	MinSpeedZ=0,	MaxSpeedZ=10000,		MaxDistanceTime=0.4f,	ClampSpeedMin=400, ClampSpeedMax=720, SpeedAddition=80.f, VaultTimeUp=0.0,	VaultTimeOver=0.35, VaultTimeDown=0.3,	OverObstacleTime = 0.2,		HandplantOffset=(X=0.f,Y=0.f,Z=5.f),		HandIKOffset=(X=0.f,Y=-7.f,Z=0.f),	LedgeOffset=(X=0.f,Y=0.f,Z=25.f),	bLeftHandIK=true,	bRightHandIK=false, 	bIsStringable=true)
VaultTypes = (AnimName="vaultOver", bVaultOnto = false,	MinHeight=64,	MaxHeight=148,	MinSpeedZ=0,	MaxSpeedZ=10000,		MaxDistanceTime=0.4f,	ClampSpeedMin=400, ClampSpeedMax=720, SpeedAddition=80.f, VaultTimeUp=0.0,	VaultTimeOver=0.35, VaultTimeDown=0.3,	OverObstacleTime = 0.2,		HandplantOffset=(X=0.f,Y=0.f,Z=5.f),		HandIKOffset=(X=0.f,Y=-7.f,Z=0.f),	LedgeOffset=(X=0.f,Y=0.f,Z=25.f),	bLeftHandIK=true,	bRightHandIK=false, 	bIsStringable=true)
VaultTypes = (AnimName="VaultOverHigh",	bVaultOnto = false, 	MinHeight=145,	MaxHeight=192,	MinSpeedZ=50,	MaxSpeedZ=10000,		MaxDistanceTime=0.4f,	ClampSpeedMin=200, ClampSpeedMax=400, VaultTimeUp=0.28, 	VaultTimeOver=0.3, VaultTimeDown=0.45,	OverObstacleTime = 0.35,	HandplantOffset=(X=0.f,Y=-40.f,Z=-69.f),	HandIKOffset=(X=0.f,Y=-7.f,Z=0.f),	LedgeOffset=(X=0.f,Y=0.f,Z=5.f),	bLeftHandIK=false,	bRightHandIK=false, bResetCamera=true )
VaultTypes = (AnimName="VaultOntoHigh", bVaultOnto = true,	MinHeight=145,	MaxHeight=192,	MinSpeedZ=50,	MaxSpeedZ=10000,		MaxDistanceTime=0.4f,	ClampSpeedMin=200, ClampSpeedMax=400, VaultTimeUp=0.27,	VaultTimeOver=0.3, VaultTimeDown=0.6,	OverObstacleTime = 0.35,	HandplantOffset=(X=0.f,Y=-65.f,Z=-15.f),	HandIKOffset=(X=0.f,Y=-7.f,Z=0.f),	LedgeOffset=(X=0.f,Y=0.f,Z=35.f),	bLeftHandIK=true,	bRightHandIK=true, bResetCamera=true )
AiAimOneShotPenalties = (Easy = 50.0, Medium = 50.0, Hard = 50.0)

[TdGame.TdMove_StepUp]
StepUpDistanceLimit=60
StepUpSpeedLimit=300;
StepUpLowMinHeight=33;
StepUpMediumMinHeight=68;
StepUpHighMinHeight=112;
StepUpHighMaxHeight=148;
StepUpOptimalLowHeight=48;
StepUpOptimalMediumHeight=88;
StepUpOptimalHighHeight=144;

[TdGame.TdMove_AutoStepUp]
StepUpDistanceLimit=60
StepUpSpeedLimit=300;
StepUpLowMinHeight=33;
StepUpMediumMinHeight=68;
StepUpHighMinHeight=8;
StepUpHighMaxHeight=48;
StepUpOptimalLowHeight=48;
StepUpOptimalMediumHeight=88;
StepUpOptimalHighHeight=144;


[TdGame.TdMove_GrabPullUp]
GrabAllowedPullUpAngle= 45
bCheckForGrab = false

[TdGame.TdMove_GrabJump]
GrabJumpOffZHeight = 160
GrabJumpPushAwayMaxSpeed= 400
GrabJumpPushAwayMinSpeed= 200
GrabAllowedJumpAngle = 45
bCheckForGrab = true
bCheckForVaultOver = true

[TdGame.TdMove_MeleeBase]
MeleeDamage=50.0f
MaxMeleeDistance=180.0f
MaxMeleeAngle=0.5f

[TdGame.TdMove_Melee]
MeleeDamage=33.5f
MeleeAssistCone=0.8f
MeleeAssistRotationTime=0.2f
BlendInMissed = 0.08f
BlendOutMissed = 0.1f

[TdGame.TdMove_MeleeAir]
MeleeDamage=100.0f
HeavyAttackHoldTime=1.4
MeleeAirAboveMinAngle=0.8
MeleeAirAboveMinSeparation=150.0
MeleeAirAboveMaxSeparation=500.0
RedoMoveTime = 0.3f

[TdGame.TdMove_MeleeAirAbove]
MeleeDamage=300.0f

[TdGame.TdMove_MeleeSlide]
MeleeDamage=60.0f
FrictionModifier=0.1f
SoccerKickDamage=60.0f

[TdGame.TdMove_MeleeWallrun]
MeleeDamage=80.0f

[TdGame.TdMove_MeleeCrouch]
MeleeDamage=33.5.0f
SpeedModifier=0.2f


[TdGame.TdMove_MeleeBarge]
MeleeDamage=50.0f
BargeMaxDistance = 500.f
BargeAdditionalUpForce = 100.f
BargeForceMultiplier = 2.4f

[TdGame.TdMove_Barge]
BargeMinTraceDistance=90
BargeAddOnSpeed=200
BargeMaxSpeed=500
BargeKickThresholdSpeed=250
RedoMoveTime = 0.1
BargeTraceTime=0.5

[TdGame.TdMove_AirBarge]
BargeMinTraceDistance=300
HeightBoostDuration = 0.25f
TotalHeightBoost = 60.f

[TdGame.TdMove_Landing]
HardLandingDamage = 15
LandingSpeedReduction = 65.f
HardLandingHeight = 530.f
SoftLandingHeight = 300.f
SkillRollLandingHeight = 200.f

[TdGame.TdMove_LayOnGround]
FrictionModifier=0.150f

[TdGame.TdMove_VaultOver]

[TdGame.TdMove_IntoClimb]
RedoMoveTime = 0.5f

[TdGame.TdMove_Climb]
IdleBlendInTime = 0.05
ClimbBlendInTime = 0.05
ClimbDownBlendInTime = 0.5
ClimbDownFastVelocity = 200
ClimbFastUpPipeAnimRate = 2.0
StartTurningAngle = 16384
AllowJumpAngle = 8192
RedoMoveTime = 0.5f

[TdGame.TdMove_ZipLine]
MinZipVelocity=300
MinZipAcceleration=400
ZipFadeInTime=0.1f
ZipFadeOutTime=0.5f
AiAimPenalties = (Easy = 0.01, Medium = 0.1, Hard = 0.3)
AIAimOneShotPenalties = (Easy = 200.0, Medium = 200.0, Hard = 200.0)

[TdGame.TdMove_IntoZipLine]
ZVelocityFallLimit=-600
IntoZiplineBlendInTime=0.3f
IntoZiplineBlendOutTime=0.2f
RedoMoveTime = 0.5f

[TdGame.TdMove_Slide]
SlideAbortSpeed=250
SlideAbortTime=2.0
FrictionModifier=0.1f
MaxFloorInclineZ=0.5
SlideSoundFadeInTime=0.1f
SlideSoundFadeOutTime=0.5f
SlideSoundAndEffectPollInterval=0.2f
AiAimPenalties = (Easy = 0.7, Medium = 0.8, Hard = 0.9)

[TdGame.TdMove_SlideBot]
SlideAbortSpeed=100
SlideAbortTime=1.0
FrictionModifier=0.035f


[TdGame.TdMove_Balance]
SpeedModifier=0.34f
RedoMoveTime = 0.5f
GravityInfluence = 0.3f
ControlInfluence = 1.5f
SpeedInfluence = 2.5f
CameraInfluence = 0.3f
TimeToCounter = 0.8f
AiAimOneShotPenalties = (Easy = 50.0, Medium = 50.0, Hard = 50.0)

[TdGame.TdMove_LedgeWalk]
SpeedModifier=0.1f

[TdGame.TdMove_GrabTransfer]
Allowed2DTransferDistance=260
AllowedZTransferDistance=140
AiAimOneShotPenalties = (Easy = 75.0, Medium = 75.0, Hard = 75.0)

[TdGame.TdMove_RumpSlide]
RedoMoveTime = 1.f
MaxSlideSpeed = 1000.f
SideControl = 350.f
GravityModifier = 0.5f
InitialSpeedLoss = 0.75f
MinSlideFloorZ = 0.9f
AiAimPenalties = (Easy = 0.01, Medium = 0.04, Hard = 0.1)
AIAimOneShotPenalties = (Easy = 200.0, Medium = 200.0, Hard = 200.0)

[TdGame.TdMove_Swing]
SwingPendulumLength = 120.f
ExitVelocityModifier = 600.f
SwingAngleTimingOffset = 1.0f
SwingExitGravityModifier = 0.75f
SwingExitGravityModifierTime = 0.70f
bCheckForGrab = true
bCheckForVaultOver = true
bCheckForWallClimb = true
bTriggersCompliment = false
AiAimPenalties = (Easy = 0.1, Medium = 0.2, Hard = 0.4)
AIAimOneShotPenalties = (Easy = 200.0, Medium = 200.0, Hard = 200.0)

[TdGame.TdMove_SwingJump]
bCheckForWallClimb = true
bCheckForGrab = true
bCheckForVaultOver = true
bTriggersCompliment = true
GravityModifier = 0.73f
GravityModifierTimer = 0.75f
TargetVolumeOffset = (X=-120.0000000,Y=0.000000,Z=-20)
AiAimPenalties = (Easy = 0.2, Medium = 0.3, Hard = 0.5)
AIAimOneShotPenalties = (Easy = 200.0, Medium = 200.0, Hard = 200.0)

[TdGame.TdMove_Coil]
HeightBoostDuration = 0.25f
TotalHeightBoost = 60.f
CoilTime = 0.5f
CoilMinTriggerSpeed = 100.f

[TdGame.TdMove_Interact]
DistanceToAButton = 48.f
DistanceToAValve = 40.0f

[TdGame.TdMove_Vertigo]
RedoMoveTime = 3.f
ZoomFOV = 84.f
ZoomRate = 30.f
ZoomOutTime = 1.2f

[TdGame.TdMove_Disarm]
AiAimPenalties = (Easy = 0.01, Medium = 0.08, Hard = 0.3)
AIAimOneShotPenalties = (Easy = 200.0, Medium = 200.0, Hard = 200.0)
RedoMoveTime = 0.2f
