extends ParkourTest

# Guards templates/base_level.tscn: the hand-authored base scene the project
# owner inherits from (Godot's "inherit scene" feature) to whitebox new
# levels quickly. Unlike scenes/main.tscn (generated by ArenaBuilder and
# regenerated/compared by test_arena.gd), nothing regenerates or otherwise
# exercises this file — every inherited level silently depends on it staying
# wired the way arena.gd, player.tscn and the tuning/HUD scripts expect.

const SCENE := "res://templates/base_level.tscn"

func _load_level() -> Node3D:
	var packed: PackedScene = ResourceLoader.load(SCENE, "", ResourceLoader.CACHE_MODE_IGNORE)
	var level = packed.instantiate()
	get_tree().root.add_child(level)
	await step(3)
	return level

func test_template_root_carries_the_arena_script_and_its_exports_resolve() -> void:
	await step(1)
	assert_true(ResourceLoader.exists(SCENE), "base_level.tscn is missing")
	var level = await _load_level()

	assert_true(level is Arena, \
		"the template root does not carry arena.gd — every inherited level would lose its Arena behaviour")
	assert_true(level.player != null, "Arena.player export did not resolve to a node")
	assert_true(level.spawn_point != null, "Arena.spawn_point export did not resolve to a node")

	level.queue_free()
	await step(1)

func test_player_and_tuning_panel_share_one_config_instance() -> void:
	await step(1)
	var level = await _load_level()

	assert_true(level.player != null, "precondition: player export must resolve")
	if level.player != null:
		assert_true(level.player.config != null, "the player did not get a MovementConfig from the arena")

	var panel = level.get_node_or_null("TuningPanel")
	assert_true(panel != null, \
		"no node named exactly \"TuningPanel\" — arena.gd finds the panel by that name at runtime, " \
		+ "so renaming it silently disables live tuning")
	if panel != null and level.player != null:
		assert_true(panel.config == level.player.config, \
			"the tuning panel and the player were handed different config objects; " \
			+ "dragging a slider would tune nothing the player actually uses")

	level.queue_free()
	await step(1)

func test_debug_hud_player_reference_resolves() -> void:
	await step(1)
	var level = await _load_level()

	var hud = level.get_node_or_null("DebugHud")
	assert_true(hud != null, "DebugHud node missing from the template")
	if hud != null:
		assert_true(hud.player == level.player, "DebugHud.player export was not wired to the arena's player")

	level.queue_free()
	await step(1)

func test_player_settles_on_the_floor_in_ground_state() -> void:
	await step(1)
	var level = await _load_level()
	await step(60)

	assert_true(level.player.is_on_floor(), "a player dropped into the template never settled onto its floor")
	assert_true(level.player.state_machine.current_name == &"Ground", \
		"player is not in Ground at rest, state = %s" % level.player.state_machine.current_name)

	level.queue_free()
	await step(1)
